---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-clone
  namespace: backup-review
  labels:
    app: postgresql-data-clone
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  accessModes:
    - ReadWriteOnce
  dataSource:
    kind: PersistentVolumeClaim
    name: postgresql-data
  resources:
    requests:
      storage: 1Gi
