---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:scc:anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: postgresql
  namespace: backup-review
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:scc:restricted
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:restricted
subjects:
- kind: ServiceAccount
  name: postgresql
  namespace: backup-review
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgresql
  namespace: backup-review
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql
  namespace: backup-review
data:
  POSTGRES_DB: example
  # POSTGRES_INITDB_ARGS: ""
  # POSTGRES_INITDB_WALDIR: /var/lib/postgresql/pg_wal
  POSTGRES_HOST_AUTH_METHOD: "md5"
  PGDATA: /var/lib/postgresql/data
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: backup-review
stringData:
  POSTGRES_USER: exampleuser
  POSTGRES_PASSWORD: examplepass
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-data
  namespace: backup-review
  labels:
    app: postgresql
data:
  db.sql: |
    -- pg_dump -U ${POSTGRES_USER} -w -d ${POSTGRES_DB}
    --
    -- PostgreSQL database dump
    --
    -- Dumped from database version 10.17 (Debian 10.17-1.pgdg90+1)
    -- Dumped by pg_dump version 13.2
    SET statement_timeout = 0;
    SET lock_timeout = 0;
    SET idle_in_transaction_session_timeout = 0;
    SET client_encoding = 'UTF8';
    SET standard_conforming_strings = on;
    SELECT pg_catalog.set_config('search_path', '', false);
    SET check_function_bodies = false;
    SET xmloption = content;
    SET client_min_messages = warning;
    SET row_security = off;
    SET default_tablespace = '';
    --
    -- Name: city; Type: TABLE; Schema: public; Owner: exampleuser
    --
    CREATE TABLE public.city (
        id integer NOT NULL,
        name character varying(64) NOT NULL
    );
    ALTER TABLE public.city OWNER TO exampleuser;
    --
    -- Name: city_id_seq; Type: SEQUENCE; Schema: public; Owner: exampleuser
    --
    CREATE SEQUENCE public.city_id_seq
        AS integer
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1;
    ALTER TABLE public.city_id_seq OWNER TO exampleuser;
    --
    -- Name: city_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: exampleuser
    --
    ALTER SEQUENCE public.city_id_seq OWNED BY public.city.id;
    --
    -- Name: country; Type: TABLE; Schema: public; Owner: exampleuser
    --
    CREATE TABLE public.country (
        id integer NOT NULL,
        name character varying(64) NOT NULL
    );
    ALTER TABLE public.country OWNER TO exampleuser;
    --
    -- Name: country_id_seq; Type: SEQUENCE; Schema: public; Owner: exampleuser
    --
    CREATE SEQUENCE public.country_id_seq
        AS integer
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1;
    ALTER TABLE public.country_id_seq OWNER TO exampleuser;
    --
    -- Name: country_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: exampleuser
    --
    ALTER SEQUENCE public.country_id_seq OWNED BY public.country.id;
    --
    -- Name: editions; Type: TABLE; Schema: public; Owner: exampleuser
    --
    CREATE TABLE public.editions (
        id integer NOT NULL,
        year integer NOT NULL,
        season integer NOT NULL,
        country integer NOT NULL,
        city integer NOT NULL
    );
    ALTER TABLE public.editions OWNER TO exampleuser;
    --
    -- Name: editions_id_seq; Type: SEQUENCE; Schema: public; Owner: exampleuser
    --
    CREATE SEQUENCE public.editions_id_seq
        AS integer
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1;
    ALTER TABLE public.editions_id_seq OWNER TO exampleuser;
    --
    -- Name: editions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: exampleuser
    --
    ALTER SEQUENCE public.editions_id_seq OWNED BY public.editions.id;
    --
    -- Name: season; Type: TABLE; Schema: public; Owner: exampleuser
    --
    CREATE TABLE public.season (
        id smallint NOT NULL,
        name character varying(10) NOT NULL
    );
    ALTER TABLE public.season OWNER TO exampleuser;
    --
    -- Name: olympics; Type: VIEW; Schema: public; Owner: exampleuser
    --
    CREATE VIEW public.olympics AS
     SELECT e.year,
        s.name AS season,
        c.name AS country,
        t.name AS city
       FROM public.editions e,
        public.season s,
        public.country c,
        public.city t
      WHERE ((e.season = s.id) AND (e.country = c.id) AND (e.city = t.id))
      ORDER BY e.id;
    ALTER TABLE public.olympics OWNER TO exampleuser;
    --
    -- Name: recent; Type: VIEW; Schema: public; Owner: exampleuser
    --
    CREATE VIEW public.recent AS
     SELECT editions.year
       FROM public.editions
      ORDER BY editions.id DESC
     LIMIT 5;
    ALTER TABLE public.recent OWNER TO exampleuser;
    --
    -- Name: latest; Type: VIEW; Schema: public; Owner: exampleuser
    --
    CREATE VIEW public.latest AS
     SELECT olympics.year,
        olympics.season,
        olympics.country,
        olympics.city
       FROM public.olympics
      WHERE (olympics.year IN ( SELECT recent.year
               FROM public.recent))
      ORDER BY olympics.year;
    ALTER TABLE public.latest OWNER TO exampleuser;
    --
    -- Name: season_id_seq; Type: SEQUENCE; Schema: public; Owner: exampleuser
    --
    CREATE SEQUENCE public.season_id_seq
        AS smallint
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1;
    ALTER TABLE public.season_id_seq OWNER TO exampleuser;
    --
    -- Name: season_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: exampleuser
    --
    ALTER SEQUENCE public.season_id_seq OWNED BY public.season.id;
    --
    -- Name: city id; Type: DEFAULT; Schema: public; Owner: exampleuser
    --
    ALTER TABLE ONLY public.city ALTER COLUMN id SET DEFAULT nextval('public.city_id_seq'::regclass);
    --
    -- Name: country id; Type: DEFAULT; Schema: public; Owner: exampleuser
    --
    ALTER TABLE ONLY public.country ALTER COLUMN id SET DEFAULT nextval('public.country_id_seq'::regclass);
    --
    -- Name: editions id; Type: DEFAULT; Schema: public; Owner: exampleuser
    --
    ALTER TABLE ONLY public.editions ALTER COLUMN id SET DEFAULT nextval('public.editions_id_seq'::regclass);
    --
    -- Name: season id; Type: DEFAULT; Schema: public; Owner: exampleuser
    --
    ALTER TABLE ONLY public.season ALTER COLUMN id SET DEFAULT nextval('public.season_id_seq'::regclass);
    --
    -- Data for Name: city; Type: TABLE DATA; Schema: public; Owner: exampleuser
    --
    COPY public.city (id, name) FROM stdin;
    1	Albertville
    2	Amsterdam
    3	Antwerp
    4	Athens
    5	Atlanta
    6	Barcelona
    7	Beijing
    8	Berlin
    9	Calgary
    10	Chamonix
    11	Cortina di Ampezzo
    12	Garmisch-Partenkirchen
    13	Grenoble
    14	Helsinki
    15	Innsbruck
    16	Lake Placid
    17	Lillehammer
    18	London
    19	Los Angeles
    20	Melbourne
    21	Mexico City
    22	Montreal
    23	Moscow
    24	Munich
    25	Nagano
    26	Oslo
    27	Paris
    28	Pyeongchang
    29	Rio de Janeiro
    30	Rome
    31	Salt Lake City
    32	Sapporo
    33	Sarajevo
    34	Seoul
    35	Sochi
    36	Squaw Valley
    37	St. Louis
    38	St. Moritz
    39	Stockholm
    40	Sydney
    41	Tokyo
    42	Turin
    43	Vancouver
    \.
    --
    -- Data for Name: country; Type: TABLE DATA; Schema: public; Owner: exampleuser
    --
    COPY public.country (id, name) FROM stdin;
    1	Australia
    2	Austria
    3	Belgium
    4	Brazil
    5	Canada
    6	China
    7	Finland
    8	France
    9	Germany
    10	Greece
    11	Italy
    12	Japan
    13	Mexico
    14	Netherlands
    15	Norway
    16	Russia
    17	South Korea
    18	Soviet Union
    19	Spain
    20	Sweden
    21	Switzerland
    22	United Kingdom
    23	United States
    24	Yugoslavia
    \.
    --
    -- Data for Name: editions; Type: TABLE DATA; Schema: public; Owner: exampleuser
    --
    COPY public.editions (id, year, season, country, city) FROM stdin;
    1	1896	1	10	4
    2	1900	1	8	27
    3	1904	1	23	37
    4	1908	1	22	18
    5	1912	1	20	39
    6	1920	1	3	3
    7	1924	2	8	10
    8	1924	1	8	27
    9	1928	2	21	38
    10	1928	1	14	2
    11	1932	2	23	16
    12	1932	1	23	19
    13	1936	2	9	12
    14	1936	1	9	8
    15	1948	2	21	38
    16	1948	1	22	18
    17	1952	2	15	26
    18	1952	1	7	14
    19	1956	2	11	11
    20	1956	1	1	20
    21	1960	2	23	36
    22	1960	1	11	30
    23	1964	2	2	15
    24	1964	1	12	41
    25	1968	2	8	13
    26	1968	1	13	21
    27	1972	2	12	32
    28	1972	1	9	24
    29	1976	2	2	15
    30	1976	1	5	22
    31	1980	2	23	16
    32	1980	1	18	23
    33	1984	2	24	33
    34	1984	1	23	19
    35	1988	2	5	9
    36	1988	1	17	34
    37	1992	2	8	1
    38	1992	1	19	6
    39	1994	2	15	17
    40	1996	1	23	5
    41	1998	2	12	25
    42	2000	1	1	40
    43	2002	2	23	31
    44	2004	1	10	4
    45	2006	2	11	42
    46	2008	1	6	7
    47	2010	2	5	43
    48	2012	1	22	18
    49	2014	2	16	35
    50	2016	1	4	29
    51	2018	2	17	28
    \.
    --
    -- Data for Name: season; Type: TABLE DATA; Schema: public; Owner: exampleuser
    --
    COPY public.season (id, name) FROM stdin;
    1	Summer
    2	Winter
    \.
    --
    -- Name: city_id_seq; Type: SEQUENCE SET; Schema: public; Owner: exampleuser
    --
    -- SELECT pg_catalog.setval('public.city_id_seq', MAX(id)) FROM city;
    -- SELECT pg_catalog.setval('public.city_id_seq', 44, false);
    SELECT pg_catalog.setval('public.city_id_seq', 44);
    --
    -- Name: country_id_seq; Type: SEQUENCE SET; Schema: public; Owner: exampleuser
    --
    -- SELECT pg_catalog.setval('public.country_id_seq', MAX(id)) FROM country;
    -- SELECT pg_catalog.setval('public.country_id_seq', 25, false);
    SELECT pg_catalog.setval('public.country_id_seq', 25);
    --
    -- Name: editions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: exampleuser
    --
    -- SELECT pg_catalog.setval('public.editions_id_seq', MAX(id)) FROM editions;
    -- SELECT pg_catalog.setval('public.editions_id_seq', 52, false);
    SELECT pg_catalog.setval('public.editions_id_seq', 52);
    --
    -- Name: season_id_seq; Type: SEQUENCE SET; Schema: public; Owner: exampleuser
    --
    -- SELECT pg_catalog.setval('public.season_id_seq', MAX(id)) FROM season;
    -- SELECT pg_catalog.setval('public.season_id_seq', 3, false);
    SELECT pg_catalog.setval('public.season_id_seq', 3);
    --
    -- Name: city city_pkey; Type: CONSTRAINT; Schema: public; Owner: exampleuser
    --
    ALTER TABLE ONLY public.city
        ADD CONSTRAINT city_pkey PRIMARY KEY (id);
    --
    -- Name: country country_pkey; Type: CONSTRAINT; Schema: public; Owner: exampleuser
    --
    ALTER TABLE ONLY public.country
        ADD CONSTRAINT country_pkey PRIMARY KEY (id);
    --
    -- Name: editions editions_pkey; Type: CONSTRAINT; Schema: public; Owner: exampleuser
    --
    ALTER TABLE ONLY public.editions
        ADD CONSTRAINT editions_pkey PRIMARY KEY (id);
    --
    -- Name: season season_pkey; Type: CONSTRAINT; Schema: public; Owner: exampleuser
    --
    ALTER TABLE ONLY public.season
        ADD CONSTRAINT season_pkey PRIMARY KEY (id);
    --
    -- PostgreSQL database dump complete
    --
