---
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: nginx-stateless
  namespace: oadp-operator
  labels:
    velero.io/storage-location: default
spec:
  includedNamespaces:
  - stateless
  storageLocation: default
