---
- name: Install and configure the Local Storage Operator
  hosts: utility
  remote_user: lab
  gather_facts: False
  module_defaults:
    group/k8s:
      host: "{{ ocp_cluster['host'] }}"
      kubeconfig: "{{ ocp_cluster['kubeconfig'] }}"
      validate_certs: "{{ ocp_cluster['validate_certs'] }}"

  roles:
    - role: ocp-install-operator
      operator: "{{ operators['lso'] }}"
    - role: ocp-localvolumes
