---
- name: Remove namespace
  hosts: utility
  remote_user: lab
  gather_facts: False
  module_defaults:
    group/k8s:
      host: "{{ ocp_cluster['host'] }}"
      kubeconfig: "{{ ocp_cluster['kubeconfig'] }}"
      validate_certs: "{{ ocp_cluster['validate_certs'] }}"

  tasks:
    - name: Remove exercise namespace
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('template', '../templates/namespace.j2') }}"
      register: remove_namespace

    - name: Monitor namespace removal
      kubernetes.core.k8s_info:
        kind: Namespace
        name: "{{ exercise['namespace']['name'] }}"
      register: monitor_namespace
      retries: 30
      delay: 2
      until: monitor_namespace['resources'] | length == 0
      when: remove_namespace['changed']
