---
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: wordpress-stateful
  namespace: oadp-operator
  labels:
    velero.io/storage-location: default
spec:
  includedNamespaces:
  - stateful
  storageLocation: default
