---
- name: Configure storage for cluster metrics
  hosts: utility
  remote_user: lab
  gather_facts: False
  module_defaults:
    group/k8s:
      host: "{{ ocp_cluster['host'] }}"
      kubeconfig: "{{ ocp_cluster['kubeconfig'] }}"
      validate_certs: "{{ ocp_cluster['validate_certs'] }}"

  roles:
    - role: ocp-ocs-metrics
      #mode: add|remove - This variable is passed by the python script.
