---
apiVersion: batch/v1
kind: Job
metadata:
  name: awscli
  namespace: oadp-operator
  labels:
    app: awscli
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: awscli
    spec:
      containers:
      - name: awscli
        image: quay.io/redhattraining/aws-cli:2.2.5
        command:
        - bash
        - -vc
        - 'aws s3 ls s3://${BUCKET_NAME} --endpoint-url=http://${BUCKET_HOST} --recursive --summarize --human-readable'
        env:
        - name: AWS_CA_BUNDLE
          value: /run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        envFrom:
        - configMapRef:
            name: backup-bucket
        - secretRef:
            name: backup-bucket
        resources: {}
      restartPolicy: Never
