---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: backup-bucket
  namespace: oadp-operator
spec:
  generateBucketName: backup-bucket
  storageClassName: ocs-storagecluster-ceph-rgw
